language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.4.6
  - DJANGO_VERSION=1.5.2
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt --use-mirrors
script:
  - cd test_project
  - python manage.py test app
notifications:
  email:
    recipients:
      - jpma55@gmail.com
    on_success: always
    on_failure: always
